# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Coordinate": "00_draw.ipynb",
         "Object": "00_draw.ipynb",
         "Shape": "00_draw.ipynb",
         "Circle": "00_draw.ipynb",
         "Text": "00_draw.ipynb",
         "Diagram": "00_draw.ipynb",
         "Rectangle": "00_draw.ipynb"}

modules = ["draw.py"]

doc_url = "https://generic-github-user.github.io/illustrious/"

git_url = "https://github.com/generic-github-user/illustrious/tree/main/"

def custom_doc_links(name): return None
