# AUTOGENERATED! DO NOT EDIT! File to edit: 00_draw.ipynb (unless otherwise specified).

__all__ = ['Coordinate', 'Object', 'Shape', 'Circle', 'Text', 'Diagram', 'Rectangle']

# Cell
from IPython.display import SVG, display
import svgwrite
import numpy as np
